:bug: Fix CS0121 error since build with .NET SDK 8.0.112
```
src/Jagabata/Resources/ResourceBase.cs(34,26): error CS0121:
 The call is ambiguous between the following methods or properties:
 'string.Split(char[]?, StringSplitOptions)' and 'string.Split(string?, StringSplitOptions)'
```